# Generated by Django 4.0.6 on 2022-08-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=70, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('fuel', models.CharField(blank=True, max_length=20, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=6, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.department')),
            ],
        ),
    ]
