# Generated by Django 4.0.6 on 2022-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
