# Generated by Django 4.0.6 on 2022-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_department_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='city',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
