# Generated by Django 4.0.6 on 2022-08-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_additions_canceledorders_location_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additions',
        ),
        migrations.DeleteModel(
            name='canceledOrders',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='automobileId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerID',
        ),
        migrations.AlterField(
            model_name='order',
            name='carModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickUp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.department'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
