# Generated by Django 4.0.6 on 2022-08-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_delete_additions_delete_canceledorders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='carModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='endRent',
            new_name='end_rent',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickUp',
            new_name='pick_up',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='startRent',
            new_name='start_rent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profilePic',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullFuel',
        ),
    ]
