# Generated by Django 4.0.6 on 2022-07-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profie_image',
            new_name='profile_image',
        ),
    ]
